# Generated by Django 5.2.6 on 2025-09-20 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('accent_color', models.CharField(default='#8B5CF6', max_length=7)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='planets/covers/')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='planets/avatars/')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('invite', 'Invite only'), ('private', 'Private')], default='public', max_length=16)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanetMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('steward', 'Steward'), ('member', 'Member')], default='member', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('can_curate', models.BooleanField(default=False)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planet_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_links', to='planets.planet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['planet__name', 'user__username'],
                'unique_together': {('planet', 'user')},
            },
        ),
        migrations.AddField(
            model_name='planet',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='planets', through='planets.PlanetMembership', through_fields=('planet', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlanetAppearance',
            fields=[
                ('planet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='appearance', serialize=False, to='planets.planet')),
                ('name', models.CharField(max_length=140)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('primary_color', models.CharField(max_length=7)),
                ('secondary_color', models.CharField(blank=True, max_length=7)),
                ('palette', models.JSONField(blank=True, default=list)),
                ('surface_type', models.CharField(choices=[('gas', 'Gas giant'), ('ice', 'Ice'), ('oceanic', 'Oceanic'), ('rocky', 'Rocky'), ('metallic', 'Metallic'), ('organic', 'Organic'), ('crystalline', 'Crystalline'), ('hybrid', 'Hybrid')], default='rocky', max_length=16)),
                ('surface_descriptors', models.JSONField(blank=True, default=list)),
                ('ring_style', models.CharField(choices=[('none', 'None'), ('single', 'Single'), ('double', 'Double'), ('multiple', 'Multiple'), ('fragmented', 'Fragmented'), ('halo', 'Halo')], default='none', max_length=16)),
                ('ring_descriptors', models.JSONField(blank=True, default=list)),
                ('ring_color', models.CharField(blank=True, max_length=7)),
                ('has_moons', models.BooleanField(default=False)),
                ('moon_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('moon_descriptors', models.JSONField(blank=True, default=list)),
                ('atmosphere_style', models.CharField(choices=[('none', 'None'), ('aurora', 'Aurora'), ('nebula', 'Nebula'), ('stormy', 'Stormy'), ('calm', 'Calm'), ('glowing', 'Glowing'), ('vaporwave', 'Vaporwave')], default='none', max_length=16)),
                ('atmosphere_descriptors', models.JSONField(blank=True, default=list)),
                ('origin_type', models.CharField(choices=[('natural', 'Natural'), ('crafted', 'Crafted'), ('reclaimed', 'Reclaimed'), ('bioengineered', 'Bioengineered'), ('ritual', 'Ritual'), ('unknown', 'Unknown')], default='natural', max_length=16)),
                ('materials', models.JSONField(blank=True, default=list)),
                ('emotional_tone', models.CharField(choices=[('sanctuary', 'Sanctuary'), ('rebellious', 'Rebellious'), ('jubilant', 'Jubilant'), ('reflective', 'Reflective'), ('fiery', 'Fiery'), ('tender', 'Tender'), ('enigmatic', 'Enigmatic'), ('custom', 'Custom')], default='sanctuary', max_length=16)),
                ('emotional_custom_label', models.CharField(blank=True, max_length=120)),
                ('accessibility_notes', models.TextField(blank=True)),
                ('custom_trigger_warnings', models.JSONField(blank=True, default=list)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='planets/hero_images/')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='planets/icons/')),
                ('hero_prompt', models.TextField(blank=True)),
                ('icon_prompt', models.TextField(blank=True)),
                ('generator_version', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('live', 'Live'), ('needs_regen', 'Needs regeneration'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_avoidance_tags', models.ManyToManyField(blank=True, related_name='planet_appearances', to='accounts.triggertopic')),
            ],
            options={
                'ordering': ['planet__name'],
            },
        ),
    ]
