# Generated by Django 5.2.6 on 2025-09-20 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetBuilderSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.PositiveSmallIntegerField(default=0)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('skipped_steps', models.JSONField(blank=True, default=list)),
                ('confirmations', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='builder_session', to='planets.planet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet_builder_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
